### ISSUE TITLE
Process execution capabilities

### ISSUE THREAD

**Issue by inkytonik** [inkytonik/cooma#26]

**Comment by inkytonik** [comment]
The idea is to add a `FileRunner` capability that takes a file name. If the named file is executable then the program gets a capability with an operation to run the program giving it strings as arguments and get back (say) the output and an error code.

**Comment by nhweston** [comment]
Testing might be a bit of a problem here due to operating systems. How should we address this?

**Comment by nhweston** [comment]
Hmm, I think I may be able to get away with just a Batch script and a Shell script. Will need to find some way to check the OS. Still not an ideal solution I guess,
