### ISSUE TITLE
Add record type concatenation

### ISSUE THREAD

**Issue by inkytonik** [inkytonik/cooma#27]
To allow more expressive types, particularly for combining capabilities, we should overload `&` to the type level to express concatenation of record types.

```
record type {x : Int}
concatenation of record types {x : Int} & {y : String}    (equiv to {x: Int, y : String}

record value (x = 3)
concatenation of record values {x = 3} & {y = “Hi”}     (equiv to {x = 3, y = “Hi”})
```

**Comment by inkytonik** [comment]
As a use case of record type concatenation we can simplify file capabilities by removing `ReaderWriter` and replacing it with `Reader & Writer`.

**Comment by nhweston** [comment]
Given that there is no syntactic distinction between terms and types, overloading `&` introduces some complications for syntactic analysis, but I think it shouldn't be too hard. In `Compiler::IsType::unapply` and `SemanticAnalyser::tipe`, I'm guessing we could just check whether the operands of `&` are types.

**Comment by inkytonik** [comment]
Yes, just check the types of the arguments. At the moment we only allow two record-typed arguments. For the type-level we can allow two type-typed arguments. I think it should work.

**Comment by nhweston** [comment]
I initially tried having `CapabilityP` represent a collection of capabilities applied to the same argument. The problem I ran into is that the compiler began generating nonsense like this:
```
letv w = cap Reader & Writer x1
```

…since `cap` is meant to construct a single record for each capability.

The approach I've taken instead is to have each separate record constructed individually. All these records are then concatenated into one.

A program accepting a single argument of `Reader & Writer` will now compile to this:

```
letv x1 = arg 0
letv c2 = {}
letv c3 = cap Reader x1
letv c4 = concat c2 c3
letv c5 = cap Writer x1
letv reader = concat c4 c5
<rest of program>
```

**Comment by inkytonik** [comment]
Creating them separately and concatenating seems like the right way to do it. It's best to treat the IR as a kind of assembly language.

Maybe you could optimise to remove `c2` and the extra concat? Seems possible since there will be at least one capability type in the concatenation of types.

**Comment by nhweston** [comment]
The same program now compiles to:

```
letv x1 = arg 0
letv c2 = cap Reader x1
letv c3 = cap Writer x1
letv rw = concat c2 c3
<rest of program>
```

**Comment by inkytonik** [comment]
Looks good.
