### ISSUE TITLE
Add folder-based reading and writing

### ISSUE THREAD

**Issue by inkytonik** [inkytonik/cooma#29]
Extend Reader and Writer so that the file name they receive can be a folder, not just a file. In the case that it's a folder name, reading and/or writing should be allowed to anywhere in that folder (including in sub-folders).

**Comment by inkytonik** [comment]
After thinking about this a bit more, I think we need to differentiate between capabilities that access files and those that access folders. If you have a capability to (say) read a folder, the "read" operation in that capability record will have to take a file name, whereas the one for Reader doesn't, since it already knows which file to read. Thus, the types need to be different.

So I think we need FolderReader and FolderWriter (better name?).

An additional complication is that traditionally reading a folder is the operation that lets you find out which files are in the folder. We might want to save FolderReader etc for those and use something else for the "can read everything below here" sort of capability.

**Comment by inkytonik** [comment]
See also #25

**Comment by nhweston** [comment]
> I think we need to differentiate between capabilities that access files and those that access folders.

The problem with this is we will probably end up having two types for every file capability (one for files, and one for folders).

One alternative that we only have the folder capability types, and if the argument is to be interpreted as just a file, the suffix parameter is just the empty string. I would point out that in most languages and libraries, there is no distinction (at the type level) between a directory and a file. I don't know enough about operating systems to explain why, but as far as I know there is good reason for this.

I don't have this fully fleshed out in my head, but perhaps there is something we could do with dependent typing in the future. For example, we have defined:

```
Directory A := {
  listFiles: Unit -> Vector String,
  listSubdirs: Unit -> Vector String,
  getFile: String -> A,
  getSubdir: String -> Directory A,
}
```

`A` could be any file capability type or concatenation thereof.

I'll do an implementation where we segregate file and folder capabilities as it may be the best solution for now.

**Comment by inkytonik** [comment]
We should also add checks that the user as read/write permission on the folder (irrespective of the files).
