### ISSUE TITLE
LUB not applied to elements of Vector expressions

### ISSUE THREAD

**Issue by nhweston** [inkytonik/cooma#53]
One would expect that `[{ a = 1, b = 2 }, { b = 3 }] : Vector({ b : Int })`. However, this is what actually happens:

```
cooma> [{ a = 1, b = 2 }, { b = 3 }]
1:2:error: all the elements in this vector must be of type { a : Int, b : Int }
[{ a = 1, b = 2 }, { b = 3 }]
 ^
```

**Comment by inkytonik** [comment]
I don't think any of the LUB stuff has made it to master yet. I haven't had time to finish that work...

**Comment by inkytonik** [comment]
Some WIP for this is in https://github.com/inkytonik/cooma/commit/48f7891bb36cf0b4a0a4288b9a657967b14c9b39. Feel free to adapt or abandon as appropriate.
